server:
  port: 8989

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: player-service
          uri: lb://PLAYER-SERVICE
          predicates:
            - Path=/players/**
          filters:
            - name: CircuitBreaker
              args:
                name: player-service
                fallbackuri: forward:/playerFallBack

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

