server:
  port: 8989

spring:
  application:
    name: GATEWAY-SERVICE

  cloud:
    gateway:
      routes:
        - id: player-service
          uri: lb://PLAYER-SERVICE
          predicates:
            - Path=/players/**
          filters:
            - name: CircuitBreaker
              args:
                name: player-service
                fallbackuri: forward:/playerFallBack

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

okta:
  oauth2:
    issuer: https://dev-2594667.okta.com/oauth2/default
    client-id: 0oajaf0xOE2DpPU1D5d5
    client-secret: XaOB4P-cZ4pSVz4DuyteUI3DFu5zqyjrexpW6HOs
  client:
    orgUrl: https://dev-2594667.okta.com
    token: 00TVXDNx1e2FgvxP4jLlONbPMzrBDLwESSf9hZSvMI123

logging:
  level:
    root: info

security:
  enable: false